#pragma once

#define HORIZONTAL_BORDER_OFFSET_RIGHT 40
#define HORIZONTAL_BORDER_OFFSET_LEFT 10
#define VERTICAL_BORDER_OFFSET 10
#define FONT_SIZE 24

#define WIDTH 635
#define HEIGHT WIDTH

#define COLLISION_K = 0.9f